### ISSUE TITLE
check and publish tumblr

### ISSUE THREAD

**Issue by meetlisa** [meetlisa/meetlisa.github.io#16]
http://prose.io/#meetlisa/meetlisa.github.io/edit/master/familyliferocks-on-tumblr.md
- [x] correction/wordsmith
- [x] post and deploy

**Comment by potzenheimer** [comment]
Hier eine Übersicht über die Korrekturen:

https://github.com/meetlisa/meetlisa.github.io/commit/d048a5e7631d42f26273bfd64ee8da04a87c0df2
